/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticationImport } from './routes/_authentication'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticationRegisterImport } from './routes/_authentication/register'
import { Route as AuthenticationLoginImport } from './routes/_authentication/login'
import { Route as AuthenticatedOnboardingImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAuthorizedImport } from './routes/_authenticated/_authorized'
import { Route as AuthenticatedAuthorizedDashboardImport } from './routes/_authenticated/_authorized/dashboard'
import { Route as AuthenticatedAuthorizedCertificateImport } from './routes/_authenticated/_authorized/certificate'
import { Route as AuthenticatedAuthorizedCoursesCourseIdImport } from './routes/_authenticated/_authorized/courses/$courseId'

// Create/Update Routes

const AuthenticationRoute = AuthenticationImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationRegisterRoute = AuthenticationRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthenticationRoute,
} as any)

const AuthenticationLoginRoute = AuthenticationLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticationRoute,
} as any)

const AuthenticatedOnboardingRoute = AuthenticatedOnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAuthorizedRoute = AuthenticatedAuthorizedImport.update({
  id: '/_authorized',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAuthorizedDashboardRoute =
  AuthenticatedAuthorizedDashboardImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAuthorizedRoute,
  } as any)

const AuthenticatedAuthorizedCertificateRoute =
  AuthenticatedAuthorizedCertificateImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => AuthenticatedAuthorizedRoute,
  } as any)

const AuthenticatedAuthorizedCoursesCourseIdRoute =
  AuthenticatedAuthorizedCoursesCourseIdImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedAuthorizedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticationImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_authorized': {
      id: '/_authenticated/_authorized'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAuthorizedImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authentication/login': {
      id: '/_authentication/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticationLoginImport
      parentRoute: typeof AuthenticationImport
    }
    '/_authentication/register': {
      id: '/_authentication/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticationRegisterImport
      parentRoute: typeof AuthenticationImport
    }
    '/_authenticated/_authorized/certificate': {
      id: '/_authenticated/_authorized/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof AuthenticatedAuthorizedCertificateImport
      parentRoute: typeof AuthenticatedAuthorizedImport
    }
    '/_authenticated/_authorized/dashboard': {
      id: '/_authenticated/_authorized/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAuthorizedDashboardImport
      parentRoute: typeof AuthenticatedAuthorizedImport
    }
    '/_authenticated/_authorized/courses/$courseId': {
      id: '/_authenticated/_authorized/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAuthorizedCoursesCourseIdImport
      parentRoute: typeof AuthenticatedAuthorizedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAuthorizedRouteChildren {
  AuthenticatedAuthorizedCertificateRoute: typeof AuthenticatedAuthorizedCertificateRoute
  AuthenticatedAuthorizedDashboardRoute: typeof AuthenticatedAuthorizedDashboardRoute
  AuthenticatedAuthorizedCoursesCourseIdRoute: typeof AuthenticatedAuthorizedCoursesCourseIdRoute
}

const AuthenticatedAuthorizedRouteChildren: AuthenticatedAuthorizedRouteChildren =
  {
    AuthenticatedAuthorizedCertificateRoute:
      AuthenticatedAuthorizedCertificateRoute,
    AuthenticatedAuthorizedDashboardRoute:
      AuthenticatedAuthorizedDashboardRoute,
    AuthenticatedAuthorizedCoursesCourseIdRoute:
      AuthenticatedAuthorizedCoursesCourseIdRoute,
  }

const AuthenticatedAuthorizedRouteWithChildren =
  AuthenticatedAuthorizedRoute._addFileChildren(
    AuthenticatedAuthorizedRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuthorizedRoute: typeof AuthenticatedAuthorizedRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthorizedRoute: AuthenticatedAuthorizedRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthenticationRouteChildren {
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationRegisterRoute: typeof AuthenticationRegisterRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationRegisterRoute: AuthenticationRegisterRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedAuthorizedRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/login': typeof AuthenticationLoginRoute
  '/register': typeof AuthenticationRegisterRoute
  '/certificate': typeof AuthenticatedAuthorizedCertificateRoute
  '/dashboard': typeof AuthenticatedAuthorizedDashboardRoute
  '/courses/$courseId': typeof AuthenticatedAuthorizedCoursesCourseIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedAuthorizedRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/login': typeof AuthenticationLoginRoute
  '/register': typeof AuthenticationRegisterRoute
  '/certificate': typeof AuthenticatedAuthorizedCertificateRoute
  '/dashboard': typeof AuthenticatedAuthorizedDashboardRoute
  '/courses/$courseId': typeof AuthenticatedAuthorizedCoursesCourseIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authentication': typeof AuthenticationRouteWithChildren
  '/_authenticated/_authorized': typeof AuthenticatedAuthorizedRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authentication/login': typeof AuthenticationLoginRoute
  '/_authentication/register': typeof AuthenticationRegisterRoute
  '/_authenticated/_authorized/certificate': typeof AuthenticatedAuthorizedCertificateRoute
  '/_authenticated/_authorized/dashboard': typeof AuthenticatedAuthorizedDashboardRoute
  '/_authenticated/_authorized/courses/$courseId': typeof AuthenticatedAuthorizedCoursesCourseIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/onboarding'
    | '/login'
    | '/register'
    | '/certificate'
    | '/dashboard'
    | '/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/onboarding'
    | '/login'
    | '/register'
    | '/certificate'
    | '/dashboard'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authentication'
    | '/_authenticated/_authorized'
    | '/_authenticated/onboarding'
    | '/_authentication/login'
    | '/_authentication/register'
    | '/_authenticated/_authorized/certificate'
    | '/_authenticated/_authorized/dashboard'
    | '/_authenticated/_authorized/courses/$courseId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/_authentication"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_authorized",
        "/_authenticated/onboarding"
      ]
    },
    "/_authentication": {
      "filePath": "_authentication.tsx",
      "children": [
        "/_authentication/login",
        "/_authentication/register"
      ]
    },
    "/_authenticated/_authorized": {
      "filePath": "_authenticated/_authorized.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_authorized/certificate",
        "/_authenticated/_authorized/dashboard",
        "/_authenticated/_authorized/courses/$courseId"
      ]
    },
    "/_authenticated/onboarding": {
      "filePath": "_authenticated/onboarding.tsx",
      "parent": "/_authenticated"
    },
    "/_authentication/login": {
      "filePath": "_authentication/login.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/register": {
      "filePath": "_authentication/register.tsx",
      "parent": "/_authentication"
    },
    "/_authenticated/_authorized/certificate": {
      "filePath": "_authenticated/_authorized/certificate.tsx",
      "parent": "/_authenticated/_authorized"
    },
    "/_authenticated/_authorized/dashboard": {
      "filePath": "_authenticated/_authorized/dashboard.tsx",
      "parent": "/_authenticated/_authorized"
    },
    "/_authenticated/_authorized/courses/$courseId": {
      "filePath": "_authenticated/_authorized/courses/$courseId.tsx",
      "parent": "/_authenticated/_authorized"
    }
  }
}
ROUTE_MANIFEST_END */
