use aes_gcm::{
    aead::{rand_core::RngCore, Aead, OsRng},
    Aes256Gcm, KeyInit, Nonce,
};
use pkcs8::DecodePublicKey;
use serde::Serialize;
use sha2::{Sha256, Digest};
use std::{
    env::temp_dir,
    error::Error,
    fs::{self, File},
    io::{Read, Write},
    path::{Path, PathBuf}, time::{SystemTime, UNIX_EPOCH},
};
use base64::{engine::general_purpose::STANDARD as B64, Engine};
use rsa::{Oaep, RsaPublicKey};
use tauri::Manager;
use zip::write::SimpleFileOptions;

use crate::db::helpers::{get_exportable_states, UserContentState};
const PUBKEY_PEM: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/key.pub"));

#[derive(Serialize)]
struct Manifest {
    #[serde(rename="WARNING")]
    warning: String,
    v: String,
    t: u64,
    key : String,
    uid: String,
}

struct EncryptionResult {
    key: String,
    bytes: Vec<u8>
}

#[tauri::command]
pub async fn export_legalese(
    app_handle: tauri::AppHandle,
    contents: String,
    suggested_name: String,
) -> Result<(), String> {
    use tauri_plugin_dialog::DialogExt;

    let path_opt = app_handle
        .dialog()
        .file()
        .add_filter("Markdown", &["md", "markdown"])
        .add_filter("Text", &["txt"])
        .set_file_name(suggested_name)
        .blocking_save_file();

    let Some(filepath) = path_opt else {
        return Ok(());
    };

    let path = filepath
        .into_path()
        .map_err(|e| format!("Could not resolve save path: {e}"))?;
    fs::write(&path, contents).map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
pub async fn export_data(
    app_handle: tauri::AppHandle,
    user_email: &str,
    destination: &str,
    informed_consent_attestation: &str,
    oatts_version: &str
) -> Result<(), String> {
    let db_path = Path::join(
        app_handle.path().app_data_dir().unwrap().as_path(),
        "test2.db",
    );
    let content_states = match get_exportable_states(db_path.as_path(), user_email).await {
        Ok(s) => s,
        Err(sqlx_err) => return Err(sqlx_err.to_string()),
    };

    match build_bundle(&content_states, destination, informed_consent_attestation, oatts_version, user_email) {
        Ok(_) => {}
        Err(err) => return Err(err.to_string()),
    };

    Ok(())
}

fn build_bundle(
    states: &Vec<UserContentState>,
    save_path: &str,
    informed_consent_attestation: &str,
    oatts_version: &str,
    user_email: &str
) -> Result<(), Box<dyn Error>> {
    let mut hasher = Sha256::new();
    hasher.update(format!("{} Oatts Salt (ew salty oats) that is only helpful for stopping rainbow tables assembled by other hacked apps, not helpful for oatts-specific rainbow tables. But it lets the same email become the same hash no matter the computer. This is the salt btw. This super crazy long string. Security is a joke.", user_email));
    let uid = format!("{:x}", hasher.finalize());

    // In an enclosure so the temp file can be dropped asap.
    let encrypted_data = { 
        let temp_path = temp_dir();
        let content_path = archive_states(states, &temp_path, informed_consent_attestation)?;
        encrypt(&content_path)
    }?;

    let manifest = Manifest {
        key: encrypted_data.key,
        t: SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs(),
        uid: uid,
        v: oatts_version.to_string(),
        warning: "WARNING: DO NOT EDIT THIS FILE. EDITING IT MAY MAKE IT IMPOSSIBLE FOR OUR RESEARCHERS TO DECRYPT IT. THANK YOU.".to_string()
    };
    let json_string = serde_json::to_string(&manifest)?;


    let path = PathBuf::from(save_path).join("oatts-data.zip");
    let file = std::fs::File::create(&path).unwrap();
    let mut zip = zip::ZipWriter::new(file);
    let zip_options = SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .compression_level(Some(5));

    zip.start_file("manifest.json", zip_options)?;
    zip.write_all(json_string.as_bytes())?;

    zip.start_file("data.enc", zip_options)?;
    zip.write_all(encrypted_data.bytes.as_slice())?;

    zip.finish()?;

    return Ok(());
}

fn encrypt(src_path: &str) -> Result<EncryptionResult, Box<dyn Error>> {
    // Get public key
    let pub_key = RsaPublicKey::from_public_key_pem(PUBKEY_PEM)?;

    // Get the raw bytes.
    let mut content_zip = File::open(src_path)?;
    let mut buffer = Vec::new();
    content_zip.read_to_end(&mut buffer)?;


    // Nonce stuff
    let mut nonce_bytes = [0u8; 12]; // AES-GCM nonce size
    OsRng.fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);
    let mut all_bytes = nonce_bytes.to_vec();

    // Generate key
    let sym_key = Aes256Gcm::generate_key(&mut OsRng);

    // Cipher key
    let padding = Oaep::new::<Sha256>();
    let mut rng = OsRng;
    let cipher_key = pub_key.encrypt(&mut rng, padding, &sym_key)?;
    
    // Encrypt file.
    let cipher = Aes256Gcm::new(&sym_key);
    let mut ciphertext = match cipher.encrypt(nonce, buffer.as_ref()) {
        Ok(c) => c,
        Err(e) => return Err(format!("Error encrypting: {}", e.to_string()).into()),
    };
    
    // Write encrypted data
    all_bytes.append(&mut ciphertext);

    let res = EncryptionResult {
        bytes: all_bytes,
        key: B64.encode(cipher_key)
    };

    Ok(res)

}

fn archive_states(
    states: &Vec<UserContentState>,
    save_path: &PathBuf,
    informed_consent_attestation: &str,
) -> zip::result::ZipResult<String> {
    let path = save_path.join("data.zip");
    let file = std::fs::File::create(&path).unwrap();
    let mut zip = zip::ZipWriter::new(file);
    let zip_options = SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .compression_level(Some(5));

    for state in states {
        let file_name = format!("{}.json", sanitize_path_component(&state.content_uri));
        zip.start_file(file_name, zip_options)?;
        zip.write_all(state.data.as_bytes())?;
    }
    zip.start_file("InformedConsentAttestation.json", zip_options)?;
    zip.write_all(informed_consent_attestation.as_bytes())?;

    zip.finish()?;
    Ok(path.display().to_string())
}

fn sanitize_path_component(input: &str) -> String {
    let mut sanitized = String::new();
    for c in input.chars() {
        if is_valid_path_char(c) {
            sanitized.push(c);
        } else {
            sanitized.push('_'); // Replace invalid characters with underscores
        }
    }
    sanitized
}

fn is_valid_path_char(c: char) -> bool {
    // Define the set of allowed characters for path components.
    // This may vary slightly depending on the operating system.
    // For simplicity, we'll allow alphanumeric characters, underscores, hyphens, and periods.
    c.is_alphanumeric() || c == '_' || c == '-' || c == '.'
}
